services:
  - type: web
    name: veb-arena-bot
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
